import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
	Upload,
	StickyNote,
	Settings,
	ChartColumnStacked,
	PanelRightOpen,
} from "lucide-react";
import Link from "next/link";
import { SideBar } from "@/components/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex h-screen w-screen bg-gray-50 ">
					<div className="w-1/5">
						<SideBar />
					</div>
					

					<div>{children}</div>
				</div>
			</body>
		</html>
	);
}
